server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    signerKey: "494ebbdf7a1eac1877ebb5e9e75c22edc17aebd86a489f575da4dfc9190d156f"
    valid-duration: 3600 # in second
    refreshable-duration: 36000 # in minute